name: Draeprogs
version: 1.0
main: me.draeprogs.customcommands.Main
description: Plugin created by Its_Destiny / DraeProgs
author: Its_Destiny/DraeProgs

commands:
    discord:
        description: Shows the server's Discord link
    website:
        description: Shows the server's Website link
    store:
        description: Shows the server's Webstore link
        aliases: [webstore]
    draeprogs:
        description: Shows the author of the plugin.
        aliases: [dpauthor]
